### ISSUE TITLE
Yes!

### ISSUE THREAD

**Issue by eggfriedrice** [lkdjiin/electr#1]
I'd find this very handy!

Python would be better for me than Ruby though.

**Comment by matthijskooijman** [comment]
Agreed on both aspects (if python, I can more easily integrate it into my IRC bot running in #arduino :-p)

**Comment by lkdjiin** [comment]
Haha, thank you ;)
I think the final program should be written in C, actually more for the portability than for the perf. But the proof of concept will be in Ruby. Not because Ruby is better than Python (it isn't) but because I could write it in a couple of days (or maybe an handful of hours) in Ruby. And also because the last time I write python code we were in another decade ;)
