### ISSUE TITLE
distinguish clearly between SI prefixes and electrical units

### ISSUE THREAD

**Issue by martindemello** [lkdjiin/electr#6]
Why is 200 ohms 200R but 200 kiloohms 2K? It should be 2kR - both with the small k as the standard SI prefix for kilo, and with the explicit R for ohms.

**Comment by lkdjiin** [comment]
I'm wondering why you are assuming that Electr should follow the SI units? What would be the advantage of using SI units?

For circuit diagrams, etc, one usually use R for ohms and K for kiloohms. Resistors are so common than this is a shortcut, I think. Sometimes you can see k instead of K.

**Comment by tnguyen14** [comment]
I agree with following SI units.

**Comment by lkdjiin** [comment]
@tnguyen14 why?

**Comment by tnguyen14** [comment]
perhaps because I'm not a practitioner of this, but I could understand standard units like martindemello suggests (200R and 2kR). I found it a lot more confusing to think of 2K as 2 kiloohms. Because what if you have 2k of another unit?

**Comment by lkdjiin** [comment]
Correct me if I'm wrong but R is not in SI units. Ω is.

If I have a kilo Watt, I could write kW, even if k and/or K is a shortcut for kilo ohm, don't you think?

There is even more possible shortcuts, sometimes you can see u for micro Farad, or n for nano Farad…

**Comment by tnguyen14** [comment]
Ahh. Then perhaps it's because I'm just not aware of these shortcuts.

**Comment by martindemello** [comment]
agreed, it seems confusing to me, but perhaps because i'm not aware of the shortcuts either. (i assumed R was because Ω is hard to type)

on the other hand, the advantage of using SI units is that they're far more universally understood. i agree that this is not necessarily a consideration if your intended audience is all familiar with the more specialised conventions.

**Comment by martindemello** [comment]
another thing to consider is that if you use SI units, you can use the prefixes as dimensionless multipliers, e.g. `100u` for `100 * 10^-6`

**Comment by jessebraham** [comment]
I was always under the impression that 200R was shorthand for 200 Ohms, and 200K was 200,000 Ohms. This is very common notation.

**Comment by FrankBuss** [comment]
The problem with 200k=200kΩ is that it is ambiguous, because I like the idea to use dimensionless multipliers. So it should always be 200kΩ (and 200kR allowed, too, for easier typing, but the output should always use Ω). If you omit the unit, most examples would still work, but the output unit would be wrong, which is no problem if you are sure that the output value is right. For learning or verification, you can always write all units and if the output unit is right, then it is a good indication that the formula is right.
+1 for SI unit prefixes, again with special conversions, like u for µ, but the output should always use µ.
Note for the manual: "SI unit" is Ω, V, A etc., a "SI prefix" or "SI metric prefix" is n, µ, m etc.
https://en.wikipedia.org/wiki/International_System_of_Units
https://en.wikipedia.org/wiki/Metric_prefix

**Comment by lkdjiin** [comment]
@FrankBuss Maybe you made another good point here ;)
To summarize your concern with a simple and trivial example, if `k` is a shortcut for kilo ohms I can write:

    E> 11k + 22k
    33k

But if all I want is to add two constants I have to do write them explicitly because I can't use `k` anymore:

    E> 11,000 + 22,000
    33,000

Is that what you mean by «dimensionless»?
